### ISSUE TITLE
Add GLFW sample

### ISSUE THREAD

**Issue by thennequin** [thennequin/ImWindow#3]
Need GLFW support for OpenGL for multi platform support.

**Comment by damiles** [comment]
Hi there is any update about this feature?

Thanks in advance.

**Comment by thennequin** [comment]
Sorry, not started yet.

**Comment by funbiscuit** [comment]
Hi!
It would be very great if you add glfw implementation. Or any other cross platform library.
I tried to do that by myself using SDL (you can look in my fork if you want) but was able to get it working only without multiwindow support. I'm not very good with sdl so I don't know how to replace some things in DX11 example and properly handle multiple windows.

Also it seems that there is a bug when you disable multiwindow support. If you start to drag a tab and release it when its over a splitter it will crash. Because it can't find a suitable position for docking.

**Comment by thennequin** [comment]
Good to known for the crash, thanks.
And actually it's not my priority to implement other system, i work with DX11.
And if i do it, it's with GLWF i think.

**Comment by thennequin** [comment]
After more than one year, the GLWF backend for ImWindow is available.
But it's only work on Windows for now, just because of 2 functions.
See the TODOs in [ImwWindowManagerGLFW.cpp](https://github.com/thennequin/ImWindow/blob/master/ImWindowGLFW/ImwWindowManagerGLFW.cpp#L36)
